#!/bin/bash
# usage: clone-microlinux <dirname>
#
# After running this script, cd into <dirname> and source the environment:
#
# cd <dirname>
# source oe-init-build-env

# Add meta-intel and meta-intel/meta-microlinux to BBLAYERS in
# build/conf/bblayers.conf e.g:

#  /home/trz/yocto/micro/meta-intel \
#  /home/trz/yocto/micro/meta-intel/meta-microlinux \

# Add chosen machine to build/conf/local.conf (before MACHINE ??= "qemux86"):
# MACHINE ?= "galileo"
# DISTRO ?= "poky-micro"

# Build the image:
# bitbake image-micro

# Create a bootable image, for example:
#
# $ wic create micro-galileo -e image-micro
#
# or
#
# $ wic create micro-minnowmax-64-usbdisk -e image-micro
#
# The output will tell you the location of the .direct image
# Burn that to the boot device and boot the board from it:
#
# $ sudo dd if=micro-galileo-201404041056-mmcblk0.direct of=/dev/sdg
#
# Just doing nothing will boot into the microLinux image
#
# The built-in IP address is 192.168.1.223.  To change it, you'll
# either need to do it manually after boot, or change the
# meta-microlinux layer and rebuild.
#
# ssh to that address and login as root with no password:
#
# $ ssh -l root 192.168.1.223
#

usage() {
    echo "Usage: $(basename $0) <dirname>"
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

mkdir $1
cd $1

git init
git remote add poky-micro https://github.com/tzanussi/poky-micro.git
git remote update
git checkout -b dizzy0 poky-micro/dizzy
git checkout -f

mkdir meta-intel
cd meta-intel
git init
git remote add meta-intel git://git.yoctoproject.org/meta-intel
git remote update
git checkout -b dizzy0 meta-intel/dizzy
git checkout -f

mkdir meta-microlinux
cd meta-microlinux
git init
git remote add meta-microlinux https://github.com/tzanussi/meta-microlinux.git
git remote update
git checkout -b dizzy0 meta-microlinux/dizzy
git checkout -f

cd ..
cd ..
