#!/bin/bash
# usage: clone-micro-galileo <dirname>
#
# After running this script, cd into <dirname> and source the environment:
#
# cd <dirname>
# source oe-init-build-env

# Add meta-intel and meta-intel/meta-micro-galileo to BBLAYERS in
# build/conf/bblayers.conf e.g:

#  /home/trz/yocto/micro/meta-intel \
#  /home/trz/yocto/micro/meta-intel/meta-micro-galileo \

# Add to build/conf/local.conf (before MACHINE ??= "qemux86"):
# MACHINE ?= "galileo"
# DISTRO ?= "poky-micro"

# Build the image:
# bitbake image-micro

# Create a bootable sdcard image:
#
# $ wic create micro-galileo -e image-micro
#
# The output will tell you the location of the .direct image
# Burn that to the sdcard and boot the galileo board from it:
#
# $ sudo dd if=micro-galileo-201404041056-mmcblk0.direct of=/dev/sdg
#
# Just doing nothing will boot into the microYocto image
#
# The built-in IP address is 192.168.1.223.  To change it, you'll
# either need to do it manually after boot, or change the
# meta-micro-galileo layer and rebuild.
#
# ssh to that address and login as root with no password:
#
# $ ssh -l root 192.168.1.223
#

mkdir $1
cd $1

git init
git remote add poky-micro https://github.com/tzanussi/poky-micro.git
git remote update
git checkout -b dizzy0 poky-micro/dizzy
git checkout -f

mkdir meta-intel
cd meta-intel
git init
git remote add meta-intel git://git.yoctoproject.org/meta-intel
git remote update
git checkout -b dizzy0 meta-intel/dizzy
git checkout -f

mkdir meta-micro-galileo
cd meta-micro-galileo
git init
git remote add meta-micro-galileo https://github.com/tzanussi/meta-micro-galileo.git
git remote update
git checkout -b dizzy0 meta-micro-galileo/dizzy
git checkout -f

cd ..
cd ..

